#!/usr/bin/env node
// Verify the built Jey plugin against a pinned, real DSH launcher in a throwaway
// DSH_HOME. Nothing here reads or writes the operator's own ~/.dsh.
import { execFileSync, spawn } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')

const argSpec = {
  dsh: '0.1.7-alpha.1',
  home: '.work/dsh-host',
  plugin: 'packages/adapter-dsh/dist/src/jey-plugin.js',
  profile: 'web',
  out: null,
  skipBoot: false,
  keepLogs: false,
}

function parseArgs(argv) {
  const out = { ...argSpec }
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i]
    if (a === '--help' || a === '-h') { usage(); process.exit(0) }
    if (!a.startsWith('--')) throw new Error(`unexpected argument ${a}`)
    const key = a.slice(2)
    if (key === 'skip-boot' || key === 'keep-logs') { out[key === 'skip-boot' ? 'skipBoot' : 'keepLogs'] = true; continue }
    if (!(key in out)) throw new Error(`unknown option --${key}`)
    out[key] = argv[i + 1]
    i += 1
  }
  return out
}

function usage() {
  console.log(`usage: node scripts/host_boot_check.mjs [--dsh <version>] [--home <dir>]
       [--plugin <path>] [--profile <name>] [--out <json>] [--skip-boot] [--keep-logs]

Boots the built plugin under a pinned DSH launcher in a temporary DSH_HOME and
records whether the host composed, rejected and accepted it. Exit code is 0 only
when every check that ran passed.`)
}

const opts = parseArgs(process.argv.slice(2))
const HOME = resolve(ROOT, opts.home)
const PROFILES = join(HOME, 'profiles')
const RUNS = join(HOME, 'runs')
const PLUGIN = resolve(ROOT, opts.plugin)

// A web boot prints a live session token in its URL line; every byte this script
// persists goes through here first.
function redact(text) {
  return String(text)
    .replace(/([?&]token=)[^\s"'&]+/g, '$1<redacted>')
    .replace(/(token[:=]\s*)[^\s"',}]+/gi, '$1<redacted>')
}

function writeRun(name, text) {
  mkdirSync(RUNS, { recursive: true })
  const path = join(RUNS, `${name}.log`)
  writeFileSync(path, redact(text))
  return path
}

function need(cond, message) {
  if (!cond) throw new Error(message)
}

/** The `reason` of the row Jey writes when it mounts, or '' when there is none. */
function mountedReason(path) {
  if (!existsSync(path)) return ''
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    if (!line.trim()) continue
    let row
    try { row = JSON.parse(line) } catch { continue }
    if (typeof row?.reason === 'string' && row.reason.startsWith('mounted:')) return row.reason
  }
  return ''
}

function install() {
  mkdirSync(PROFILES, { recursive: true })
  const manifest = join(PROFILES, 'package.json')
  const wanted = {
    name: 'jey-host-boot-profiles',
    private: true,
    version: '0.0.0',
    dependencies: { '@deepseek-ai/dsh': opts.dsh },
  }
  const bin = join(PROFILES, 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js')
  const current = installedVersion()
  if (current === opts.dsh && existsSync(bin)) return { bin, installed: current, reinstalled: false }
  writeFileSync(manifest, `${JSON.stringify(wanted, null, 2)}\n`)
  console.log(`installing @deepseek-ai/dsh@${opts.dsh} into ${PROFILES}${current ? ` (found ${current})` : ''} …`)
  execFileSync('npm', ['install', '--no-audit', '--no-fund', '--loglevel=error'], {
    cwd: PROFILES, stdio: 'inherit', shell: process.platform === 'win32',
  })
  need(existsSync(bin), `npm install finished without ${bin}`)
  const after = installedVersion()
  need(after === opts.dsh, `requested ${opts.dsh} but the launcher reports ${after}`)
  return { bin, installed: after, reinstalled: true }
}

function installedVersion() {
  const p = join(PROFILES, 'node_modules', '@deepseek-ai', 'dsh', 'package.json')
  if (!existsSync(p)) return null
  return JSON.parse(readFileSync(p, 'utf8')).version
}

function overlay(body) {
  const path = join(HOME, `${body.id}.patch.yml`)
  writeFileSync(path, `# Generated by scripts/host_boot_check.mjs — do not edit.\n- insert:\n    - id: jey\n      name: '${PLUGIN.replaceAll('\\', '/')}'\n      config:\n${body.config}`)
  return path
}

const OFF_BODY = {
  id: 'jey-off',
  config: `        schemaVersion: '1'
        mode: off
        provider:
          kind: unconfigured
        egress:
          mode: deny
        limits: {}
        features: {}
        audit: {}
`,
}

const SHADOW_BODY = {
  id: 'jey-shadow',
  config: `        schemaVersion: '1'
        mode: shadow
        provider:
          kind: mock
        egress:
          mode: deny
        limits: {}
        features: {}
        audit: {}
`,
}

// enforce on synthetic answers must be refused at load; that refusal is what proves
// the host executed our apply().
const BAD_BODY = {
  id: 'jey-bad',
  config: `        schemaVersion: '1'
        mode: enforce
        provider:
          kind: mock
        egress:
          mode: deny
        limits: {}
        features: {}
        audit: {}
`,
}

function run(bin, args, { timeoutMs = 120_000, env = {} } = {}) {
  return new Promise(res => {
    const child = spawn(process.execPath, [bin, ...args], {
      cwd: HOME, env: { ...process.env, DSH_HOME: HOME, ...env }, stdio: ['ignore', 'pipe', 'pipe'], shell: false,
    })
    let out = ''
    child.stdout.on('data', d => { out += d })
    child.stderr.on('data', d => { out += d })
    const timer = setTimeout(() => { child.kill('SIGTERM') }, timeoutMs)
    const settled = new Promise(r => child.on('exit', code => r(code)))
    settled.then(code => {
      clearTimeout(timer)
      res({ code, text: out })
    })
  })
}

/** Wait until the launcher says it is listening, then tear it down. */
async function bootUntilReady(bin, args, { marker, timeoutMs = 120_000, env = {} } = {}) {
  const child = spawn(process.execPath, [bin, ...args], {
    cwd: HOME, env: { ...process.env, DSH_HOME: HOME, ...env }, stdio: ['ignore', 'pipe', 'pipe'], shell: false,
  })
  let out = ''
  let treeFailed = false
  const stop = () => { try { child.kill('SIGTERM') } catch { /* already gone */ } }
  const result = await new Promise(res => {
    const timer = setTimeout(() => res({ outcome: 'timeout' }), timeoutMs)
    const onData = d => {
      out += d
      if (/plugin tree failed to load/.test(out)) treeFailed = true
      if (marker.test(out)) { clearTimeout(timer); res({ outcome: 'ready' }) }
      if (treeFailed) { clearTimeout(timer); res({ outcome: 'tree-failed' }) }
    }
    child.stdout.on('data', onData)
    child.stderr.on('data', onData)
    child.on('exit', code => { clearTimeout(timer); res({ outcome: 'exited', code }) })
  })
  stop()
  await new Promise(res => (child.exitCode === null ? child.on('close', res) : res()))
  return { ...result, text: out }
}

/** `--port 0` lets the launcher pick; it then prints the URL it is serving. */
const LISTEN_ARGS = ['--host', '127.0.0.1', '--port', '0', '--no-open']

async function main() {
  need(existsSync(PLUGIN), `built plugin not found at ${PLUGIN} — run \`pnpm -r build\` first`)
  mkdirSync(HOME, { recursive: true })
  const { bin, installed } = install()
  const version = execFileSync(process.execPath, [bin, '--version'], {
    cwd: HOME, env: { ...process.env, DSH_HOME: HOME }, encoding: 'utf8', shell: false,
  }).trim()

  const off = overlay(OFF_BODY)
  const shadow = overlay(SHADOW_BODY)
  const bad = overlay(BAD_BODY)

  const checks = []
  const record = (name, pass, detail) => { checks.push({ name, pass, detail }); console.log(`${pass ? 'PASS' : 'FAIL'}  ${name} — ${detail}`) }
  /** `pass` alone hides *why*; keep the reason visible in the committed evidence too. */
  const summarize = c => `${c.name}: ${c.detail.replace(/[A-Za-z]:[\\/][^\s]+/g, '<path>')}`
  /** Facts about how this launcher version behaves, which we observe but do not control. */
  const observations = []
  const observe = (name, value) => { observations.push({ name, value }); console.log(`NOTE  ${name} — ${value}`) }

  // 1. Does the launcher compose our overlay at all?
  const dumped = await run(bin, ['--profile', opts.profile, '--patch', off, '--dump-config'], { timeoutMs: 60_000 })
  const dumpText = dumped.text
  writeRun('dump-config', dumpText)
  record('dump-config exits 0', dumped.code === 0, `exit=${dumped.code}`)
  record('dump-config names the built plugin', dumpText.includes(PLUGIN.replaceAll('\\', '/')), `entry present=${dumpText.includes(PLUGIN.replaceAll('\\', '/'))}`)
  record('dump-config carries the jey id', /id: ['"]?jey/.test(dumpText), 'composed entry with id jey')

  // 2. A config Jey refuses has to surface *our* message from inside the host: that text
  // can only come from apply() having run. Whether the launcher then aborts or serves on
  // without Jey is the host's policy, so it is recorded, not asserted.
  const badAudit = join(HOME, 'bad-audit.jsonl')
  rmSync(badAudit, { force: true })
  const refused = await bootUntilReady(bin, ['--profile', opts.profile, '--patch', bad, ...LISTEN_ARGS], {
    marker: /dsh web: http/i, timeoutMs: 90_000, env: { JEY_AUDIT_PATH: badAudit },
  })
  const refusedLog = writeRun('bad-config', refused.text)
  record('bad config is refused by Jey, not by the host', /invalid Jey configuration/.test(refused.text) && /ENFORCE_WITH_MOCK/.test(refused.text), `ConfigError surfaced, outcome=${refused.outcome} log=${refusedLog}`)
  record('a refused config leaves no mount row', mountedReason(badAudit) === '', `journal=${badAudit}`)
  observe('launcher reaction to a refused plugin', `${/plugin tree failed to load/.test(refused.text) ? 'aborted the plugin tree' : 'no plugin-tree failure message'}; boot outcome=${refused.outcome}; still serving=${/dsh web: http/i.test(refused.text)}`)

  // 3. Accepted configurations must mount and serve. The launcher's startup log exporter
  // is warn-level, so a plugin's own info line never reaches the console; the journal is
  // what proves the mount, and "listening" alone would prove only that the host booted.
  if (!opts.skipBoot) {
    const offAudit = join(HOME, 'off-audit.jsonl')
    rmSync(offAudit, { force: true })
    const offBoot = await bootUntilReady(bin, ['--profile', opts.profile, '--patch', off, ...LISTEN_ARGS], {
      marker: /dsh web: http/i, timeoutMs: 120_000, env: { JEY_AUDIT_PATH: offAudit },
    })
    const offLog = writeRun('boot-off', offBoot.text)
    record('off mode serves', /dsh web: http/i.test(offBoot.text), `outcome=${offBoot.outcome} log=${offLog}`)
    record('off mode mounted', mountedReason(offAudit).startsWith('mounted:mode=off provider=unconfigured egress=deny'), `journal=${offAudit}`)

    const shadowAudit = join(HOME, 'shadow-audit.jsonl')
    rmSync(shadowAudit, { force: true })
    const shadowBoot = await bootUntilReady(bin, ['--profile', opts.profile, '--patch', shadow, ...LISTEN_ARGS], {
      marker: /dsh web: http/i, timeoutMs: 120_000, env: { JEY_AUDIT_PATH: shadowAudit },
    })
    const shadowLog = writeRun('boot-shadow', shadowBoot.text)
    record('shadow mode mounts with a provider', mountedReason(shadowAudit).startsWith('mounted:mode=shadow provider=mock'), `journal=${shadowAudit} log=${shadowLog}`)
    // Nothing drove a model turn, so one row is the whole expected journal; a second row
    // here would mean Jey judged a call that never happened.
    observe('shadow boot journal rows', existsSync(shadowAudit) ? readFileSync(shadowAudit, 'utf8').split('\n').filter(Boolean).length : 0)
  } else {
    observe('boots', 'NOT_RUN (--skip-boot): only the composed tree and the refused config were exercised')
  }

  const failed = checks.filter(c => !c.pass)
  const evidence = {
    schemaVersion: '1',
    checkedOn: new Date().toISOString().slice(0, 10),
    launcher: { requested: opts.dsh, resolvedVersion: version, installedPrefix: installed, profile: opts.profile },
    plugin: PLUGIN.replaceAll('\\', '/'),
    home: HOME.replaceAll('\\', '/'),
    checks: checks.map(c => ({ ...c, detail: summarize(c) })),
    observations,
    verdict: failed.length === 0 ? 'PASS' : 'FAIL',
    // A boot that reached "listening" is not the same as a boot that mounted Jey, and
    // no tool call happened in either, so this says nothing about decision quality.
    scope: 'launcher composition and plugin acceptance only; no model turn was driven',
  }
  const outPath = resolve(ROOT, opts.out ?? join(HOME, 'host_boot.json'))
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, `${JSON.stringify(evidence, null, 2)}\n`)
  console.log(`\n${failed.length === 0 ? 'all checks passed' : `${failed.length} check(s) failed`} — evidence: ${outPath.replaceAll('\\', '/')}`)
  process.exit(failed.length === 0 ? 0 : 1)
}

main().catch(err => { console.error(`host_boot_check: ${err.message}`); process.exit(2) })
